In [2]:
#!pip install numpy

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2.size

6

In [9]:
arr2.shape

(2, 3)

In [10]:
arr2.ndim

2

In [11]:
arr3 = np.array([1,2,3,4]).reshape(2,2)

In [12]:
arr3

array([[1, 2],
       [3, 4]])

In [13]:
arr4 = np.arange(1,10).reshape(3,3)

In [14]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr5 = np.arange(1,13).reshape(4,3)

In [16]:
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.linspace(1,10,12, dtype=int).reshape(3,4)

array([[ 1,  1,  2,  3],
       [ 4,  5,  5,  6],
       [ 7,  8,  9, 10]])

In [18]:
np.random.rand(3,3)

array([[0.75004685, 0.05151695, 0.68541649],
       [0.66004183, 0.33750575, 0.8200898 ],
       [0.51975879, 0.67439936, 0.55902782]])