In [2]:
#!pip install numpy

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2.size

6

In [9]:
arr2.shape

(2, 3)

In [10]:
arr2.ndim

2

In [11]:
arr3 = np.array([1,2,3,4]).reshape(2,2)

In [12]:
arr3

array([[1, 2],
       [3, 4]])

In [13]:
arr4 = np.arange(1,10).reshape(3,3)

In [14]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr5 = np.arange(1,13).reshape(4,3)

In [16]:
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.linspace(1,10,12, dtype=int).reshape(3,4)

array([[ 1,  1,  2,  3],
       [ 4,  5,  5,  6],
       [ 7,  8,  9, 10]])

In [102]:
(np.random.rand(3,3)*10).astype(int)

array([[2, 7, 8],
       [0, 4, 6],
       [6, 2, 1]])

In [105]:
zero=np.zeros((3,4)).astype(int)

In [106]:
zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [107]:
one=np.ones((3,4)).astype(int)

In [108]:
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [109]:
a= np.arange(1,9).reshape(2,4)
b= np.arange(9,17).reshape(2,4)

In [110]:
a+b

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [111]:
a-b

array([[-8, -8, -8, -8],
       [-8, -8, -8, -8]])

In [112]:
c= np.arange(1,9).reshape(4,2)

In [114]:
a.dot(c)

array([[ 50,  60],
       [114, 140]])

In [115]:
a=np.array([20,30,40,50])
b= np.arange(4)
c= a-b

In [116]:
b**2
10*np.sin(a)
a<35

array([ True,  True, False, False])

In [ ]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
A*B # element wise multiplication
A.dot(B) # for matix multiplication
A@B # for matrix multiplication

array([[5, 4],
       [3, 4]])

In [118]:
a= np.random.random((2,3))
a

array([[0.72583791, 0.29524772, 0.21923135],
       [0.13732165, 0.54941099, 0.32359584]])

In [ ]:
# indexing and slicing


In [119]:
myarray= np.arange(1,17).reshape(4,4)

In [ ]:
myarray.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [121]:
myarray[2]

array([ 9, 10, 11, 12])

In [122]:
myarray[2][2]

np.int64(11)

In [123]:
myarray[1,1]

np.int64(6)

In [124]:
myarray[1:3,1]

array([ 6, 10])

In [127]:
myarray[2:,2:]

array([[11, 12],
       [15, 16]])

In [128]:
myarray[2:,2:].flatten()

array([11, 12, 15, 16])

In [ ]:
# stacking array

In [132]:
a=np.floor(10*np.random.random((2,2)))
b=np.floor(10*np.random.random((2,2)))

In [137]:
c=np.floor(10*np.random.random((2,2)))
c


array([[6., 7.],
       [5., 7.]])

In [143]:
d=np.int32(10*np.random.random((2,2)))
d

array([[7, 4],
       [9, 8]], dtype=int32)

In [133]:
# stacking arrays
np.vstack((a,b))

array([[0., 3.],
       [3., 8.],
       [5., 3.],
       [4., 6.]])

In [131]:
# stacking horizontally
np.hstack((a,b))

array([[7., 5., 4., 2.],
       [0., 3., 7., 4.]])

In [144]:
c = np.floor(10*np.random.random((2,12)))

In [145]:
c

array([[5., 3., 0., 4., 4., 1., 5., 1., 9., 7., 7., 1.],
       [8., 0., 7., 2., 0., 5., 5., 6., 2., 6., 5., 1.]])

In [146]:
np.hsplit(c,3)

[array([[5., 3., 0., 4.],
        [8., 0., 7., 2.]]),
 array([[4., 1., 5., 1.],
        [0., 5., 5., 6.]]),
 array([[9., 7., 7., 1.],
        [2., 6., 5., 1.]])]

In [147]:
np.vsplit(c,2)

[array([[5., 3., 0., 4., 4., 1., 5., 1., 9., 7., 7., 1.]]),
 array([[8., 0., 7., 2., 0., 5., 5., 6., 2., 6., 5., 1.]])]

In [148]:
d= np.arange(1,10)
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
bool_arr = d%2==0 # booloean array
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False])

In [151]:
d[bool_arr] #filtering even numbers

array([2, 4, 6, 8])

In [152]:
f = np.arange(1,5).reshape(2,2)

In [153]:
f

array([[1, 2],
       [3, 4]])

In [154]:
f.transpose()

array([[1, 3],
       [2, 4]])

In [155]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
np.diagonal(f)

array([1, 4])

In [157]:
np.trace(f)

np.int64(5)

In [158]:
!pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 497.5 kB/s eta 0:00:22
   - -------------------------------------- 0.5/11.0 MB 497.5 kB/s eta 0:00:22
   - -------------------------------------- 0.5/11.0 MB 497.5 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/11.0 MB 518.3 kB/s eta 0:00:20
   -- ------------------------------------- 0.8/11.0 MB 518.3 kB/s eta 0:00:20
   --- ------------------------------------ 1